#!/usr/bin/env bash
# WAVRICK AI 台本パイプライン（Whisper + Grok）セットアップガイド
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "=== WAVRICK AI 台本パイプライン セットアップ ==="
echo ""
echo "【必要なもの】"
echo "  1. Supabase プロジェクト（接続済み）"
echo "  2. OpenAI API キー（Whisper）"
echo "  3. xAI API キー（Grok）https://console.x.ai/"
echo "  4. YouTube 音声プロキシ（このリポジトリ同梱）を公開 URL で Edge から叩けること"
echo ""
echo "【手順 A】Supabase CLI を入れる（未導入なら）"
echo "  brew install supabase/tap/supabase"
echo "  supabase login"
echo "  cd $ROOT && supabase link --project-ref gdolqgcftxqxaacjyqla"
echo "  ※ project-ref はダッシュボード URL の /project/XXXX の部分"
echo ""
echo "【手順 B】Edge Function をデプロイ"
echo "  supabase functions deploy media-pipeline"
echo ""
echo "【手順 C】Secrets を設定"
echo "  supabase secrets set \\"
echo "    OPENAI_API_KEY=sk-... \\"
echo "    XAI_API_KEY=xai-... \\"
echo "    YOUTUBE_AUDIO_PROXY_URL=https://YOUR_PUBLIC_URL/extract \\"
echo "    YOUTUBE_AUDIO_PROXY_SECRET=wavrick-local-dev-secret"
echo ""
echo "  任意: GROK_MODEL=grok-4.3  （旧 grok-2-latest / grok-3 は利用不可）"
echo ""
echo "【手順 D】音声プロキシを起動（別ターミナル）"
echo "  方法1 Docker:"
echo "    docker compose up --build"
echo "  方法2 Python:"
echo "    cd services/youtube-audio-proxy"
echo "    pip3 install -r requirements.txt"
echo "    PROXY_SECRET=wavrick-local-dev-secret PORT=5055 python3 app.py"
echo ""
echo "【手順 E】ローカルプロキシを Supabase から見えるようにする"
echo "  Edge はクラウド上で動くため localhost:5055 は直接届きません。"
echo "  ngrok 例:"
echo "    ngrok http 5055"
echo "  cloudflared 例（ngrok 未導入時）:"
echo "    ./scripts/start-audio-tunnel.sh"
echo "  secrets 反映:"
echo "    ./scripts/set-youtube-proxy-secrets.sh https://xxxx.ngrok-free.app"
echo "    ./scripts/set-youtube-proxy-secrets.sh https://xxxx.trycloudflare.com"
echo ""
echo "  ※ Cursor 内ターミナルで HTTP_PROXY が付くと yt-dlp が失敗することがあります。"
echo "    通常の macOS ターミナルで ./scripts/start-audio-proxy.sh を実行してください。"
echo ""
echo "【手順 F】アプリで試す"
echo "  python3 -m http.server 8080  # または 8888"
echo "  依頼フォーム → 動画URL → 「動画URLから台本を自動生成」"
echo ""
echo "【DB】media_pipeline_jobs テーブルは supabase-setup.sql に含まれます（未実行なら SQL Editor で実行）"
echo ""
