#!/usr/bin/env bash
# YouTube チャンネル所有確認（Google OAuth）セットアップガイド
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
REF="gdolqgcftxqxaacjyqla"
CALLBACK="https://${REF}.supabase.co/functions/v1/youtube-oauth-callback"
START_TEST="https://${REF}.supabase.co/functions/v1/youtube-oauth-start?channel_key=handle:test&parent_origin=http://localhost:8889"

echo "=== WAVRICK YouTube OAuth セットアップ ==="
echo ""
echo "【A】Google Cloud Console（https://console.cloud.google.com/）"
echo "  1. プロジェクトを作成 or 選択"
echo "  2. API とサービス → ライブラリ → 「YouTube Data API v3」を有効化"
echo "  3. API とサービス → OAuth 同意画面"
echo "     - ユーザータイプ: 外部（テスト中はテストユーザーを追加）"
echo "     - スコープ: .../auth/youtube.readonly"
echo "  4. API とサービス → 認証情報 → 認証情報を作成 → OAuth クライアント ID"
echo "     - アプリケーションの種類: ウェブアプリケーション"
echo "     - 承認済みのリダイレクト URI（これだけでOK）:"
echo "       ${CALLBACK}"
echo "     - 承認済みの JavaScript 生成元（任意・ローカル用）:"
echo "       http://localhost:8889"
echo "       http://127.0.0.1:8889"
echo ""
echo "【B】Supabase secrets（Cursor ターミナル）"
echo "  ./scripts/set-youtube-oauth-secrets.sh"
echo "  または:"
echo "  supabase secrets set \\"
echo "    GOOGLE_CLIENT_ID=xxxx.apps.googleusercontent.com \\"
echo "    GOOGLE_CLIENT_SECRET=GOCSPX-xxxx \\"
echo "    YOUTUBE_OAUTH_STATE_SECRET=\$(openssl rand -hex 32)"
echo ""
echo "【C】Edge Functions をデプロイ"
echo "  supabase functions deploy youtube-oauth-start youtube-oauth-callback"
echo ""
echo "【D】ブラウザで試す"
echo "  http://localhost:8889 → YouTuber依頼フォーム"
echo "  チャンネルURL（例: https://www.youtube.com/@あなたのハンドル）"
echo "  → 「2) Googleでチャンネル所有を確認」"
echo "  ※ ポップアップ許可 / file:// では不可"
echo ""
echo "【動作確認】start が 302 なら secrets + デプロイ OK の目安:"
echo "  curl -sI \"${START_TEST}\" | head -5"
echo ""
